In [1]:
import torch

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### Random tensors

why random tensors


Randome tesors are important becuase the way many neural networks learn is that they start with tensors with tensorf full of randome and then adjust those randome numbers to better represent the data

`Start with randome numbers -> look at the data -> update random numbers -> look at the data -> update random numbers`


In [8]:
#  crearte a randome tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.7574, 0.9797, 0.3164, 0.7813],
        [0.6453, 0.2258, 0.6177, 0.1818],
        [0.2223, 0.4695, 0.4524, 0.2173]])

In [9]:
random_tensor = torch.rand(10, 10, 10)
random_tensor

tensor([[[0.0607, 0.6300, 0.1407, 0.1161, 0.4734, 0.9925, 0.1049, 0.9640,
          0.1628, 0.1008],
         [0.1860, 0.6404, 0.7153, 0.7784, 0.8869, 0.3039, 0.3232, 0.9888,
          0.5634, 0.2243],
         [0.1045, 0.8055, 0.5829, 0.5375, 0.2511, 0.4130, 0.9561, 0.7795,
          0.6478, 0.7356],
         [0.1117, 0.5881, 0.9414, 0.7448, 0.2893, 0.3419, 0.8006, 0.9201,
          0.8815, 0.6467],
         [0.4784, 0.9494, 0.9976, 0.0324, 0.2724, 0.8218, 0.1415, 0.3002,
          0.9019, 0.8924],
         [0.1531, 0.7680, 0.9144, 0.8659, 0.2072, 0.9864, 0.2248, 0.4575,
          0.0544, 0.4484],
         [0.9023, 0.5826, 0.4607, 0.9935, 0.3751, 0.8919, 0.0775, 0.9052,
          0.7168, 0.4213],
         [0.9174, 0.1392, 0.7256, 0.2435, 0.2337, 0.9169, 0.6966, 0.0437,
          0.6449, 0.6404],
         [0.7867, 0.1920, 0.0131, 0.7785, 0.7677, 0.6909, 0.5598, 0.7240,
          0.3157, 0.0763],
         [0.6341, 0.6880, 0.0901, 0.9889, 0.2340, 0.7053, 0.2443, 0.3518,
          0.3556,

In [10]:
10*10*10

1000

In [11]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height , widht and colour channle ( Red, Green, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
random_image_size_tensor

tensor([[[0.2326, 0.6987, 0.6026],
         [0.3974, 0.7736, 0.6465],
         [0.5919, 0.3600, 0.6925],
         ...,
         [0.8347, 0.7367, 0.3264],
         [0.2161, 0.9376, 0.0369],
         [0.6691, 0.3501, 0.5351]],

        [[0.9743, 0.6460, 0.7316],
         [0.5977, 0.9309, 0.8383],
         [0.0087, 0.6713, 0.9202],
         ...,
         [0.1687, 0.4580, 0.9913],
         [0.8372, 0.1001, 0.5035],
         [0.1487, 0.8059, 0.2600]],

        [[0.5165, 0.4838, 0.9687],
         [0.8364, 0.2498, 0.5925],
         [0.7384, 0.8951, 0.1666],
         ...,
         [0.7674, 0.4953, 0.6944],
         [0.2256, 0.4157, 0.8932],
         [0.2533, 0.7724, 0.6194]],

        ...,

        [[0.4326, 0.8994, 0.1004],
         [0.5934, 0.6252, 0.1058],
         [0.8706, 0.5666, 0.0881],
         ...,
         [0.2059, 0.3604, 0.1170],
         [0.6065, 0.7659, 0.7087],
         [0.8469, 0.3640, 0.0774]],

        [[0.9629, 0.6573, 0.8469],
         [0.2444, 0.1351, 0.6629],
         [0.

In [13]:
torch.rand((3,3, 1))

tensor([[[0.9810],
         [0.8485],
         [0.9820]],

        [[0.7565],
         [0.5517],
         [0.1107]],

        [[0.4788],
         [0.6391],
         [0.6472]]])

### Zeros and Ones

In [14]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4 ))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
### creating a range of tensors

one_to_ten = torch.arange(0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [17]:
# creating tensos like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
 device=None,
requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [20]:
int_32_tensor =  torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [21]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### GEtting information from tensors

1. **Tensors not right datatype** - to do get datatype from a tensor, can use the `tensor.dtype`
2. **Tensors not right shape** - tp get shape from a tensor, can use `tensor.shape`
3. **Tensors not on the right device** - to get device from a tensor, can use tensor.device



In [23]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3702, 0.1591, 0.7877, 0.4556],
        [0.5346, 0.0415, 0.5917, 0.4421],
        [0.1343, 0.1618, 0.0733, 0.5802]])

In [24]:
# Find out details about somoe tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.3702, 0.1591, 0.7877, 0.4556],
        [0.5346, 0.0415, 0.5917, 0.4421],
        [0.1343, 0.1618, 0.0733, 0.5802]])
Datatype of tensor: torch.float32
Device Tensor is on: cpu


In [25]:
print(f"Shape of tensor: {some_tensor.size()}")

Shape of tensor: torch.Size([3, 4])


### Manipulating tensors

### Manipulating Tensors

Tensors operations includem:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication 
    

In [26]:
# create a tensor
tensor = torch.tensor([1, 2, 3])
tensor+ 10

tensor([11, 12, 13])

In [27]:
# mulitply by 10
tensor* 10

tensor([10, 20, 30])

In [28]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###  Matrix Multiplication 

Two main ways of peroforming Multiplication in neural networks and deep learning

1. Element-wise Multiplication
2. Matrix multiplication


More information on multiplying metrics: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [29]:
# Element wise mutliplication

tensor * tensor

tensor([1, 4, 9])

In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensorA = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensorB = torch.tensor([[7, 10],
                        [8, 11]])

torch.mm(tensorA, tensorB)

tensor([[ 23,  32],
        [ 53,  74],
        [ 83, 116]])

In [32]:
tensorA.T

tensor([[1, 3, 5],
        [2, 4, 6]])

### Finding the min, max, mean sum, etc (tensor aggregation)

In [33]:
x = torch.arange(0, 100, 10)

In [34]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
torch.max(x)

tensor(90)

In [37]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [38]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.argmin()

tensor(0)

In [41]:
x.argmax()

tensor(9)

### Reshapping, stacking, squeezing and unsqueezzing tensors

* Reshaping: - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of centerain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - Return a view of input with dimensions permuted (swapped) in a certain way 


In [42]:
# 1. Let's creeate a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
# Add an extra dimmenstion
x_reshapped = x.reshape((1, 9))
x_reshapped, x_reshapped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
x_reshpaed = x.reshape(3, 3)
x_reshpaed, x_reshpaed.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [45]:
#change the view

z = x.view(1, 9)
z.shape, z

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

> **Note**: changing the `z` would change the x as well bcs `z` and `x` both share the same memory

In [46]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [47]:
# Sack tensors onthe top of each other
x_stacked = torch.stack([x, x, x, x])


In [48]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
x_reshapped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_reshpaed.shape

torch.Size([3, 3])

In [51]:
x_reshaped = x_reshapped.squeeze()

In [52]:
x_reshaped.shape

torch.Size([9])

In [53]:
# torch.unsqueeze() -  adds a single dimnestion to a target tensor at a specific dim (dimmenstion)
print(f"Previous target: {x_reshaped}")
print(f"Previous shape:  {x_reshaped.shape}")

x_unsqeezed = torch.unsqueeze(x_reshaped, dim=1)

print(f"New target: {x_unsqeezed}")
print(f"New shape:  {x_unsqeezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:  torch.Size([9])
New target: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:  torch.Size([9, 1])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing in numpy


In [54]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
# Let's index on our new tensor
x[0, :2, 1]

tensor([2, 5])

In [55]:
x_squeezed = x.squeeze()
x_squeezed

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Pytorch tensors & Numpy

NumPy is a popular scientific Python numcerical computing library 

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor -> `torch.form_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [84]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # when converting from numpy to pytorch, pytorch reflexcts numpy's deafult datatpe of float64 unless specified otherwise
array, tensor

## if we want to change the dtype 

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [86]:
tensor.dtype

torch.float32

In [88]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to 'numpy_tensor`
# `

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random
 seed**

Essentially what the randome seed does is "flavour" the randomness

In [91]:
import torch

# create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B==random_tensor_A)

tensor([[0.9852, 0.7546, 0.5623, 0.8118],
        [0.7187, 0.5504, 0.5731, 0.4981],
        [0.8844, 0.4717, 0.7599, 0.9545]])
tensor([[0.8066, 0.1070, 0.1761, 0.3754],
        [0.6020, 0.4405, 0.3643, 0.9056],
        [0.6737, 0.5468, 0.8544, 0.8155]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
# Let's make some random but reproducible tensors

import torch


# set the random seed
RANDOM_SEED  =  42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computation)

GPUs = faster computationl on numbers, thanks to CUDA  + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory (good).


### Getting a GPU

1. Easiest - Use Google Colab for a free 
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...., see this post for what optioms to get:
https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use Cloud Computing




In [101]:
!nvidia-smi

Thu Mar  7 11:07:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050        Off | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8              N/A /  35W |      6MiB /  3072MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [102]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [105]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models ) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations


In [106]:
# Create a tensor (default on the GPU)

tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [107]:
# Move tensor to GPU ( if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu  

tensor([1, 2, 3], device='cuda:0')

## Moving tenors back to CPU

In [109]:
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [111]:
# to fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])